name: CI-CD nfs-mobile

on:
  push:
    branches: [ master, dev ]
jobs:
  build-react-native:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run test Jest
        run: npm test

      - name: Build APK 
        run: cd android && chmod +x gradlew && ./gradlew assembleRelease
        # Partie déploiment UNIQUEMENT ANDROID SSH
      - name: Installation ssh
        uses: shimataro/ssh-key-action@v2
        with:
          # Secret Key a renseigné dans les secrets GITHUB
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'random-string-text'

      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      # User et Host a renseigné dans les secrets GITHUB 
      # Exemple: ssh noel@xx.xxx.xx.xxx mkdir -p ./mobile/apk-nfs-mobile
      - name: Create Directory apk-nfs-mobile
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} mkdir -p ./mobile/apk-nfs-mobile

      - name: Deploy the apk on the server 
        run: rsync -avz ./android/app/build/outputs/apk/release/app-release.apk ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:~/mobile/apk-nfs-mobile
      
      - name: Rename Directory apk-nfs-mobile for versioning
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} 'mv ~/mobile/apk-nfs-mobile ~/mobile/apk-nfs-mobile_$(date +%Y-%m-%d:%H-%M-%S)'
        #Exemple de résulat : /mobile/apk-nfs-mobile_2022-10-16:13-36-07